from PyQt5.QtCore import QSettings

__author__ = 'saflores'

from gui.gen.preferences import Ui_preferences

class PreferencesDialog(Ui_preferences):
    """
    This Class extends the Ui_preferences generated by QT designer so that we can
    add stuff or modify it's behaviour without editing the generated code.
    """
    ####################################################################################################################
    def __init__(self, dialog_p):
        super().__init__()
        self.setupUi(dialog_p)
        self.dialog = dialog_p

        mySettings = QSettings(QSettings.IniFormat, QSettings.UserScope, 'Sogeti', 'validate')

        # image quality value is 120 by default, unless the user set it to something else
        qv = 110
        #if mySettings.contains('report/imageQuality'):
        try:
            qv = int(mySettings.value('report/imageQuality'))
        except TypeError:
            # most likely the key is not present in the config. The default value will be used
            pass
        except ValueError:
            # config is not semantically correct (NaN). The default value will be used
            pass

        self.spinBox.setValue(qv)

