from PyQt5.QtCore import QSettings

__author__ = 'saflores'

from gui.gen.preferences import Ui_preferences

class PreferencesDialog(Ui_preferences):
    """
    This Class extends the Ui_preferences generated by QT designer so that we can
    add stuff or modify it's behaviour without editing the generated code.
    """
    ####################################################################################################################
    def __init__(self, dialog_p):
        super().__init__()
        self.setupUi(dialog_p)
        self.dialog = dialog_p

        mySettings = QSettings(QSettings.IniFormat, QSettings.UserScope, 'Sogeti', 'validate')

        qv = 120
        if mySettings.contains('report/imageQuality'):
            qv = int(mySettings.value('report/imageQuality'))

        self.spinBox.setValue(qv)
